all:
	gcc -Wall -Wextra -Werror \
		calculate_limits.c \
		case_1_2.c \
		case_1_3.c \
		case_1_4.c \
		case_2_1.c\
		incrementate.c\
	   	case_2_2.c\
	   	case_2_2_A.c\
	   	case_2_2_B.c\
	   	case_2_3.c\
	   	case_3_1.c\
	   	case_3_2.c\
	   	case_4_1.c\
	   	checker.c\
	   	count_right.c\
	   	count_left.c\
	   	ft_error_message.c \
		get_input.c\
	   	inicializate.c\
	   	loop.c\
	   	main.c \
	   	switcher.c\
	   	vld.c
